def complement (dna):
    dna = dna.replace("A", "X")
    dna = dna.replace("T", "Y")
    dna = dna.replace("C", "W")
    dna = dna.replace("G", "Z")
    return dna.replace("X", "T").replace("Y", "A").replace("W", "G").replace("Z", "C")

def reverse_complement (dna):
    complement_dna = complement (dna)
    return print(complement_dna [::-1])

dna = "AAATCCGCGACCGGTGGAATTCCCAGGCTTATGTGGAGGTATAACTCTCGCTCGAAGCCTTCGTCGCAGGTCACGTAGCGCGCAATTTGACTCAGACCTAAGGCTGCCGAGGGCTCGGCCCGTGAGTGTTGAACAATCCTGCCAAGATACTAGTATCCCCCTCATGTGAGTTTGTATTGCGAAAGTCCCGCGTGGAAAAATAAACCTCACAATCTCCGTTTCATCACTGAACTATCCAAGCCGCGACAGCGGAGAGTGTCTATGCCACTTTACGCACCCGATCGTGTCGTTGCGACTCTTAAGGTTGAATCACGGCGGGTCCCTGCAACTGATAAGAACGATTCTCCTTGACAACTCCACCGAGCTCTTCCTGAGACGTATGCTAACCTTATCATCCCGCGGCGCTCCCGATGGCGAGACCTGGGTCATTAGAATGTATGAGCAGTTTCTCTTGTCATGAAACGGAAGAATTATGGTCTTTGAAAACCGTCCATCACGGTAGCTGCTTCGTAATTAGATCGCCATGAGTGATGCCGGCAAGACCGGGCATGAAGATTTCTGAAGAAAATCAGTAATTCGCTACTAATTCCCTGATATAACATGAACCATTCTTACGCAACTGACGGTACATTGGCGATCGACAAATTGGGCGCTGGGTAGATCGGATCGAGTAGAATAGCTTGGATGCAGAGACTCACACTAGACCGGCTCATTTCACCTAGCTGGGCAGTCCGAGCCTAATTCCCAGAAAGCCACGACCATGGGTACTTGCGGGAGGAGTACCACATCAGCTCGGTATACCATTATCGTATTGCG"
reverse_complement (dna)